#!/bin/sh

echo "Is is morning? Please answer yes or no"
read time

case "$time" in 
	yes) echo "Good morning";;
	no) echo "Good afternoon";;
	y) echo "Good morning";;
	n) echo "Good afternoon";;
	*) echo "Sorry, answer not recongnized";;
esac

exit 0 
